// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7a1pUjfOyTfQtsMfkdYs6LghAl9EqRxE',
    appId: '1:760079685871:android:710aae945e636c85d8631a',
    messagingSenderId: '760079685871',
    projectId: 'fir-pary',
    storageBucket: 'fir-pary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmc2kORlD_Xk4ggGYKd7AFbxkEGaqAQ_8',
    appId: '1:760079685871:ios:d754a85623a6675cd8631a',
    messagingSenderId: '760079685871',
    projectId: 'fir-pary',
    storageBucket: 'fir-pary.appspot.com',
    iosClientId: '760079685871-ivoau09rrcq0a2ik0f3n9rd83opa8gmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.spray',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmc2kORlD_Xk4ggGYKd7AFbxkEGaqAQ_8',
    appId: '1:760079685871:ios:8c42a7d8e52f38b9d8631a',
    messagingSenderId: '760079685871',
    projectId: 'fir-pary',
    storageBucket: 'fir-pary.appspot.com',
    iosClientId: '760079685871-0o987d1q05mejlserf7j31g9r2c8ev5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
